import { Injectable, Logger } from '@nestjs/common';
import { createHash } from 'crypto';
import type { Prisma } from '@prisma/client';
import { PrismaService } from '../../infra/database/prisma.service.js';

/**
 * Plan J (F-32) — tamper-evident audit-log writer.
 *
 * Each AuditLog row stores `hashSelf` (SHA-256 of its canonical fields
 * plus the previous row's hashSelf) and `hashPrev` (the previous row's
 * hashSelf). The chain is scoped per tenant: each tenant has its own
 * independent chain so a tenant deletion can't break other tenants.
 *
 * Verification (`verify`) walks the chain in createdAt order and
 * recomputes each row's expected hash; mismatch = tampering.
 *
 * Legacy rows (pre-Plan-J) carry NULL hashSelf and are skipped — chain
 * verification begins at the first row that has hashSelf set.
 */
export interface WriteAuditLogInput {
  tenantId: string;
  userId?: string | null;
  action: string;
  resource: string;
  resourceId: string;
  beforeState?: Prisma.InputJsonValue | null;
  afterState?: Prisma.InputJsonValue | null;
  ipAddress?: string | null;
}

@Injectable()
export class AuditChainService {
  private readonly logger = new Logger(AuditChainService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Insert a new AuditLog row with hash chaining. Pass a transaction
   * client when calling from inside a Prisma `$transaction`; otherwise
   * the service uses its own PrismaService.
   */
  async write(
    input: WriteAuditLogInput,
    tx?: Prisma.TransactionClient,
  ): Promise<void> {
    const client = tx ?? this.prisma;
    try {
      // Pull the latest chained row for this tenant to chain off of.
      const previous = await client.auditLog.findFirst({
        where: { tenantId: input.tenantId, hashSelf: { not: null } },
        orderBy: { createdAt: 'desc' },
        select: { hashSelf: true },
      });
      const hashPrev = previous?.hashSelf ?? null;

      // createdAt is generated by Postgres on insert. To keep the hash
      // deterministic AND chain-safe, we compute hashSelf AFTER the row
      // is inserted (so the timestamp is known), then UPDATE the row in
      // the same statement set. This is two queries but avoids a clock
      // skew between app and DB.
      const created = await client.auditLog.create({
        data: {
          tenantId: input.tenantId,
          userId: input.userId ?? null,
          action: input.action,
          resource: input.resource,
          resourceId: input.resourceId,
          beforeState: (input.beforeState ?? undefined) as Prisma.InputJsonValue | undefined,
          afterState: (input.afterState ?? undefined) as Prisma.InputJsonValue | undefined,
          ipAddress: input.ipAddress ?? null,
          hashPrev,
        },
        select: {
          id: true,
          tenantId: true,
          userId: true,
          action: true,
          resource: true,
          resourceId: true,
          beforeState: true,
          afterState: true,
          ipAddress: true,
          createdAt: true,
        },
      });

      const hashSelf = this.computeHash(created, hashPrev);
      await client.auditLog.update({
        where: { id: created.id },
        data: { hashSelf },
      });
    } catch (err) {
      // Audit is observability, not source-of-truth — never bubble a
      // logging failure into the actual request.
      this.logger.error(
        `[AuditChainService.write] failed for ${input.resource}:${input.resourceId}: ${(err as Error)?.message}`,
        (err as Error)?.stack,
      );
    }
  }

  /**
   * Walk a tenant's chain in createdAt order and re-derive every row's
   * expected hashSelf. Returns the first mismatch, or `null` if the
   * chain is intact.
   */
  async verify(tenantId: string): Promise<{
    ok: boolean;
    checked: number;
    firstBadId?: string;
    reason?: string;
  }> {
    const rows = await this.prisma.auditLog.findMany({
      where: { tenantId, hashSelf: { not: null } },
      orderBy: { createdAt: 'asc' },
      select: {
        id: true,
        tenantId: true,
        userId: true,
        action: true,
        resource: true,
        resourceId: true,
        beforeState: true,
        afterState: true,
        ipAddress: true,
        createdAt: true,
        hashSelf: true,
        hashPrev: true,
      },
    });

    let prevHash: string | null = null;
    for (const r of rows) {
      if (r.hashPrev !== prevHash) {
        return {
          ok: false,
          checked: rows.indexOf(r),
          firstBadId: r.id,
          reason: 'hash_prev mismatch (chain link broken)',
        };
      }
      const expected = this.computeHash(r, prevHash);
      if (expected !== r.hashSelf) {
        return {
          ok: false,
          checked: rows.indexOf(r),
          firstBadId: r.id,
          reason: 'hash_self mismatch (row body tampered)',
        };
      }
      prevHash = r.hashSelf;
    }
    return { ok: true, checked: rows.length };
  }

  /**
   * Canonical SHA-256. JSON.stringify ordering is fixed by spec for
   * objects with string keys, so we sort keys explicitly to guarantee
   * identical output across Node versions.
   */
  private computeHash(row: any, prevHash: string | null): string {
    const canonical = {
      tenantId: row.tenantId,
      userId: row.userId ?? null,
      action: row.action,
      resource: row.resource,
      resourceId: row.resourceId,
      beforeState: row.beforeState ?? null,
      afterState: row.afterState ?? null,
      ipAddress: row.ipAddress ?? null,
      createdAt:
        row.createdAt instanceof Date
          ? row.createdAt.toISOString()
          : row.createdAt,
      hashPrev: prevHash,
    };
    const serialized = JSON.stringify(canonical, Object.keys(canonical).sort());
    return createHash('sha256').update(serialized).digest('hex');
  }
}
