export const PARTICIPANT_STATUS = {
  INQUIRY: 'INQUIRY',
  DOCUMENTS_PENDING: 'DOCUMENTS_PENDING',
  FEE_PENDING: 'FEE_PENDING',
  ACTIVE: 'ACTIVE',
  ON_HOLD: 'ON_HOLD',
  COMPLETED: 'COMPLETED',
  WITHDRAWN: 'WITHDRAWN',
} as const;
