export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  LOCATION_MANAGER = 'LOCATION_MANAGER',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  STAFF = 'STAFF',
}

export const USER_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  LOCATION_MANAGER: 'LOCATION_MANAGER',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  STAFF: 'STAFF',
} as const;
